version: '3.8'

services:
  fetcher-and-q1-function:
    image: "fetcher-q1:test" # This is done by building the docker file that is in VM1/ and naming it like so <-
    environment:
      RAY_ADDRESS: "ray-head:6379"
    deploy:
      placement:
        constraints: [node.hostname == grupp12-vm-1]
    depends_on:
    - ray-head
    - ray-worker

  q2-function:
    image: "q2-function:test" # This is done locally by building the docker file in VM2/
    environment:
      RAY_ADDRESS: "ray-head:6379"
    deploy:
      placement:
        constraints: [node.hostname == grupp12-vm-2]
    depends_on:
      - ray-head

  q3-4-function:
    image: "q3-4-function:test" # Repeated after locally building the dockerfile in VM3/ dir
    environment:
      RAY_ADDRESS: "ray-head:6379"
    deploy:
      placement:
        constraints: [node.hostname == grupp12-vm-3]
    depends_on:
      - ray-head

  ray-head:
    image: rayproject/ray:2.46.0
    command: >
      bash -c "ray stop; sleep 5; ray start --head --node-ip-address=0.0.0.0 --port=6379 --disable-usage-stats ; sleep 10 ; trap : TERM INT; sleep infinity"
    ports:
      - "6379:6379"    
      - "8265:8265"    
      - "10001:10001"
    deploy:
      placement:
        constraints: [node.hostname == grupp12-vm-1]

  ray-worker:
    image: rayproject/ray:2.46.0
    command: >
      bash -c "ray stop; sleep 10; ray start --address=ray-head:6379 ; trap : TERM INT; sleep infinity"
    deploy:
      placement:
        constraints:
          - node.labels.ray.role == worker
    depends_on:
      - ray-head
