version: '3.8'

services:
  fetcher-and-q1-function:
    image: fetcher-and-q1
    build: 
      context: /project/VM1
      dockerfile: /project/VM1/Dockerfile
    deploy:
      placement:
        constraints: [node.hostname == grupp12-vm-1]

  q2-function:
    image: q2-function
    build: 
      context: /project/VM2
      dockerfile: /project/VM2/Dockerfile
    deploy:
      placement:
        constraints: [node.hostname == grupp12-vm-2]
    depends_on:
      - fetcher-and-q1

  q3-4-function:
    image: q3-4-function
    build: 
      context: /project/VM3
      dockerfile: /project/VM3/Dockerfile
    deploy:
      placement:
        constraints: [node.hostname == grupp12-vm-3]
    depends_on:
      - fetcher-and-q1

        # frontend:
        #image: yourregistry/frontend:latest
        #deploy:
        #placement:
        #constraints: [node.hostname == frontend-node]
        #ports:
        #- "80:80"

