FROM python:3.11-bookworm
ENV GITHUB_TOKEN="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"
WORKDIR /project/VM3
RUN pip install -r ../requirements.txt
ENTRYPOINT ["python"]
CMD ["./Q3_Q4.py"]